model:
  name: SimpleCAE64
  # name: SimpleCAE16
  hyper_parameters:
    input_channels: 1
    latent_dimensions: 16
    encoder_base_channels: 64
    decoder_base_channels: 64
    encoder_actfunc: relu
    decoder_actfunc: relu
    encoder_output_actfunc: relu
    decoder_output_actfunc: sigmoid
train:
  # trained_save_path: SimpleCAE64/2023-01-31/12-54-00
  # trained_save_path: ${model.name}/2023-11-27/12-07-16
  trained_save_path: ${model.name}/2024-02-06/16-17-13
  train_hyperparameter:
    lr: 0.001
    epochs: 100
    batch_size: 128
    reconst_loss: bce
    latent_loss: null
    num_save_reconst_image: 10
    early_stopping: true
dataset:
  image_target: CNTForest
  train_path: data/processed/CNTForest/cnt_sem_64x64/10k
  check_path: data/processed/check/CNTForest/cnt_sem_for_check_64x64/10k
  transform:
    Grayscale: 1
    ToTensor: 0
# model:
#   name: SimpleCVAE_softplus32
#   hyper_parameters:
#     input_channels: 1
#     latent_dimensions: 10
#     encoder_base_channels: 64
#     decoder_base_channels: 64
#     encoder_actfunc: selu
#     decoder_actfunc: selu
#     encoder_output_actfunc: selu
#     decoder_output_actfunc: sigmoid
# train:
#   trained_save_path: SimpleCVAE_softplus32/2023-07-18/11-43-58/
#   train_hyperparameter:
#     lr: 0.001
#     epochs: 100
#     batch_size: 128
#     reconst_loss: bce
#     latent_loss: softplus
#     num_save_reconst_image: 5
#     early_stopping: false
# dataset:
#   image_target: CNTForest
#   train_path: data/processed/CNTForest/cnt_sem_32x32/10k
#   check_path: data/processed/check/CNTForest/cnt_sem_for_check_32x32/10k
#   transform:
#     Grayscale: 1
#     ToTensor: 0

feature_save_path: ${model.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

hydra:
  run:
    dir: ./reports/features/${train.trained_save_path}
