model:
  name: SimpleCAE16
  hyper_parameters:
    input_channels: 1
    latent_dimensions: 128
    encoder_base_channels: 64
    decoder_base_channels: 64
    encoder_actfunc: "selu"
    decoder_actfunc: "selu"
    encoder_output_actfunc: "selu"
    decoder_output_actfunc: "sigmoid"

train:
  trained_save_path: ${model.name}/2025-02-04/08-12-21
  train_hyperparameter:
    lr: 1.0e-3
    epochs: 1000
    batch_size: 128
    reconst_loss: bce
    latent_loss: null
    num_save_reconst_image: 5
    early_stopping: True

dataset:
  image_target: CNTForest
  train_path: ./data/processed/CNTForest/cnt_sem_16x16/10k
  check_path: ./data/processed/check/CNTForest/cnt_sem_for_check_16x16/10k
  transform:
    Grayscale: 1
    ToTensor: 0

feature_save_path: ${train.trained_save_path}

hydra:
  run:
    dir: ./reports/features/${train.trained_save_path}
