name: SimpleCAE64
hyper_parameters:
  input_channels: 1
  latent_dimensions: 128
  encoder_base_channels: 64
  decoder_base_channels: 64
  encoder_actfunc: "leakyrelu"
  decoder_actfunc: "leakyrelu"
  encoder_output_actfunc: "leakyrelu"
  decoder_output_actfunc: "relu"
