[project]
name = "feat-extrc"
version = "0.1.0"
description = "Feature extraction from CNTs forest cross sectional image"
authors = [{ name = "Ryuichi Shinsei", email = "275051h@gs.kochi-tech.ac.jp" }]
requires-python = "~=3.10"
readme = "README.md"
license = "MIT"
dependencies = [
    "numpy>=1.25.0,<2",
    "jupyter>=1.0.0,<2",
    "matplotlib>=3.9.3,<4",
    "polars>=0.18.3,<0.19",
    "scikit-learn>=1.2.2,<2",
    "hydra-core>=1.3.2,<2",
    "torchinfo>=1.8.0,<2",
    "torch>=2.0.1,<3",
    "torchvision>=0.15.2,<0.16",
    "pandas>=2.0.3,<3",
    "tqdm>=4.65.0,<5",
    "einops>=0.6.1,<0.7",
    "seaborn>=0.12.2,<0.13",
    "pyarrow>=12.0.1,<13",
    "opencv-python>=4.8.0.74,<5",
    "optuna>=3.4.0,<4",
    "umap-learn>=0.5.4,<0.6",
    "omegaconf>=2.3.0,<3",
    "onnx>=1.15.0,<2",
    "tensorboard>=2.18.0,<3",
    "torch-tb-profiler>=0.4.3,<0.5",
    "torcheval>=0.0.7,<0.0.8",
    "japanize-matplotlib>=1.1.3,<2",
]

[project.scripts]
export_log = "src.utilities.export_tb_log:run"

[dependency-groups]
dev = [
    "mypy>=1.4.0,<2",
    "types-pillow>=10.1.0.2,<11",
    "ruff>=0.9.7,<0.10",
    "pytest>=8.3.3,<9",
]

[[tool.uv.index]]
name = "torch_cu118"
url = "https://download.pytorch.org/whl/cu118"
explicit = true

[tool.uv.sources]
torch = { index = "torch_cu118" }
torchvision = { index = "torch_cu118" }

[tool.hatch.build.targets.sdist]
include = ["src"]

[tool.hatch.build.targets.wheel]
include = ["src"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.mypy]
# エラー時のメッセージを詳細表示
show_error_context = true
# エラー発生箇所の行数/列数を表示
show_column_numbers = true
# import 先のチェックを行わない (デフォルトだとサードパーティーライブラリまでチェックする)
ignore_missing_imports = true
# 関数定義の引数/戻り値に型アノテーション必須
disallow_untyped_defs = true
# デフォルト引数に None を取る場合型アノテーションに Optional 必須
no_implicit_optional = true
# 戻り値が Any 型ではない関数の戻り値の型アノテーションが Any のとき警告
warn_return_any = true
# mypy エラーに該当しない箇所に `# type: ignore` コメントが付与されていたら警告
# ※ `# type: ignore` が付与されている箇所は mypy のエラーを無視出来る
warn_unused_ignores = true
# 冗長なキャストに警告
warn_redundant_casts = true

[tool.ruff]
exclude = [
    ".venv",
    "venv",
    "__pycache__",
    ".git",
]
line-length = 79
indent-width = 4

[tool.ruff.lint]
select = [
    "C",
    "E",
    "F",
    "ARG",
    "I",
    "W",
]
ignore = [

]
fixable = ["ALL"]
unfixable = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
