model:
  name: SimpleCAE16
  hyper_parameters:
    input_channels: 1
    latent_dimensions: 128   # default: 128
    encoder_base_channels: 64
    decoder_base_channels: 64
    encoder_activation: "selu"
    decoder_activation: "selu"
    encoder_output_activation: "selu"
    decoder_output_activation: "sigmoid"

train:
  trained_save_path: ${model.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  train_hyperparameter:
    lr: 5e-4
    epochs: 100
    batch_size: 128
    reconst_loss: bce
    latent_loss: null
    num_save_reconst_image: 10
    early_stopping: True

dataset:
  image_target: CNTForest
  path: ./data/processed/CNTForest/cnt_sem_16x16/10k
  transform:
    Grayscale: 1
    RandomHorizontalFlip: 0.5
    ToTensor: 0

hydra:
  run:
    dir: ./models/${train.trained_save_path}
