model:
  name: ClassifierCNTforest
  feature:
    network_type: DownSamplingResNet
    pretrained_path: null
    hyper_parameters:
      input_channels: 1
      inplanes: 64
      layers:
        - 3
        - 4
        - 6
        - 3
      output_channels: 32
      block_name: basicblock
      activation: relu
  classifier:
    network_type: MLP
    pretrained_path: null
    hyper_parameters:
      input_dimension: ${model.feature.hyper_parameters.output_channels}
      middle_dimensions:
        - 100
      output_dimension: 9
      activation: relu

train:
  trained_save_path: ${model.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  train_hyperparameter:
    lr: 1.0e-4
    epochs: 100
    batch_size: 64
    reconst_loss: ce
    latent_loss: null
    num_save_reconst_image: 10
    early_stopping: True

dataset:
  image_target: CNTForest
  path: ./data/processed/CNTForest/cnt_sem_64x64/10k
  transform:
    Grayscale: 1
    RandomHorizontalFlip: 0.5
    ToTensor: 0

hydra:
  run:
    dir: ./models/${train.trained_save_path}
